# Generated by Django 3.2.6 on 2021-08-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_foto_receita2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='foto_receita2',
        ),
    ]
